server:
  port: 8081
spring:
  application:
    name: Customer
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://homeserverlm99.servebeer.com:8087/amigosservices_customer?createDatabaseIfNotExist=true
    password: Admin@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true