server:
  port: 8082
spring:
  application:
    name: fraud
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://homeserverlm99.servebeer.com:8087/amigosservices_fraud?createDatabaseIfNotExist=true
    password: Admin@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka